### PR TITLE
Update ci-build.yaml

### PR DESCRIPTION
**Pull request by Psynosaur**
Try this?

### CODE REVIEW

**Comment by F5OEO** [comment]
Test has failed..

**Comment by Psynosaur** [comment]
> Test has failed..

Error: Resource not accessible by integration

Kindly suggests that you change your action permissions.

https://github.com/orgs/community/discussions/60820#discussioncomment-6445895
image

This could also be related to the unmerged pull request.

Therefor my repository (from which I made branch `patch-1`) doesn't have the required permissions to create a release on you repo, since I am not a contributor yet.

This build as is passes on my fork(with my repo token for the actions, since I'm the main contributor.
image

Please fix permissions, or accept pull request.

Since we can't create a release from a test run.

**Comment by Psynosaur** [comment]
Flashed the ci build `pluto.frm`

We have no local spectrum

image

when we tx, it sends the RF to qo-100 briefly and then drops, but shows up on local spectrum as TXing...?

image

With the PA off, this is the result.

image

we are missing the NB(faintly) and the WB beacon

Reverting to 0.3-31

**Comment by F5OEO** [comment]
Can you try the latest 33 ?

**Comment by F5OEO** [comment]
Nothing broken ?

**Pull request merged**
